import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Shop",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  },
  {
    _id: 1005,
    title: "Journal",
    link: "/journal",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boys' caps come in various styles and designs, providing a versatile accessory to complement their outfits and add a touch of personal flair.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "The tea table is a stylish and functional piece of furniture, serving as a central hub for sharing conversations and enjoying tea in a cozy setting.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Headphones are audio devices worn over the ears, delivering immersive sound and providing a personalized listening experience for music, calls, or other audio content.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Sunglasses are stylish accessories that provide protection against harmful UV rays while adding a touch of flair to one's appearance.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boys' caps come in various styles and designs, providing a versatile accessory to complement their outfits and add a touch of personal flair.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "The tea table is a stylish and functional piece of furniture, serving as a central hub for sharing conversations and enjoying tea in a cozy setting.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Headphones are audio devices worn over the ears, delivering immersive sound and providing a personalized listening experience for music, calls, or other audio content.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Sunglasses are stylish accessories that provide protection against harmful UV rays while adding a touch of flair to one's appearance.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A flower base serves as a decorative vessel designed to hold and display a bouquet of flowers, adding a touch of elegance and charm to any space.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "The new backpack features a sleek design, ample storage space, and innovative organizational compartments for both style and practicality.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Household materials encompass a wide range of essential items and products used in daily domestic life, including furniture.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "The travel bag is a versatile and essential accessory designed to accommodate and organize belongings for convenient and efficient journeys.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "The round table clock adorned the center of the room, its timeless design complementing the decor with elegance and precision.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A cloth basket is a versatile and lightweight storage solution, ideal for organizing and transporting laundry or various household items.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },
  {
    _id: 1013,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },

  {
    _id: 1014,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1015,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },
  {
    _id: 1016,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "The travel bag is a versatile and essential accessory designed to accommodate and organize belongings for convenient and efficient journeys.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "The round table clock adorned the center of the room, its timeless design complementing the decor with elegance and precision.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A cloth basket is a versatile and lightweight storage solution, ideal for organizing and transporting laundry or various household items.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Headphones are audio devices worn over the ears, delivering immersive sound and providing a personalized listening experience for music, calls, or other audio content.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Sunglasses are stylish accessories that provide protection against harmful UV rays while adding a touch of flair to one's appearance.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A flower base serves as a decorative vessel designed to hold and display a bouquet of flowers, adding a touch of elegance and charm to any space.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boys' caps come in various styles and designs, providing a versatile accessory to complement their outfits and add a touch of personal flair.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "Tea Table",
    price: "180.00",
    color: "Gray",
    badge: true,
    des: "The tea table is a stylish and functional piece of furniture, serving as a central hub for sharing conversations and enjoying tea in a cozy setting.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Headphones are audio devices worn over the ears, delivering immersive sound and providing a personalized listening experience for music, calls, or other audio content.",
  },
  {
    _id: 1027,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Sunglasses are stylish accessories that provide protection against harmful UV rays while adding a touch of flair to one's appearance.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A flower base serves as a decorative vessel designed to hold and display a bouquet of flowers, adding a touch of elegance and charm to any space.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "New Backpack",
    price: "180.00",
    color: "Gray",
    badge: false,
    des: "The new backpack features a sleek design, ample storage space, and innovative organizational compartments for both style and practicality.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Household materials",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Household materials encompass a wide range of essential items and products used in daily domestic life, including furniture.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "The travel bag is a versatile and essential accessory designed to accommodate and organize belongings for convenient and efficient journeys.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "The round table clock adorned the center of the room, its timeless design complementing the decor with elegance and precision.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A cloth basket is a versatile and lightweight storage solution, ideal for organizing and transporting laundry or various household items.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },
  {
    _id: 1036,
    img: newArrTwo,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },
  {
    _id: 1037,
    img: newArrFour,
    productName: "Funny toys for babies",
    price: "60.00",
    color: "Mixed",
    badge: false,
    des: "Funny toys for babies often feature whimsical designs and playful sounds, captivating their curiosity and eliciting joyous giggles during playtime.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Travel Bag",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "The travel bag is a versatile and essential accessory designed to accommodate and organize belongings for convenient and efficient journeys.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Round Table Clock",
    price: "44.00",
    color: "Black",
    badge: true,
    des: "The round table clock adorned the center of the room, its timeless design complementing the decor with elegance and precision.",
  },
  {
    _id: 1041,
    img: newArrTwo,
    productName: "Smart Watch",
    price: "250.00",
    color: "Black",
    badge: true,
    des: "A smartwatch is a wearable device that combines fitness tracking, notifications, and often connectivity to smartphones, providing users with a multifaceted and convenient gadget on their wrists.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "cloth Basket",
    price: "80.00",
    color: "Mixed",
    badge: true,
    des: "A cloth basket is a versatile and lightweight storage solution, ideal for organizing and transporting laundry or various household items.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Headphones",
    price: "25.00",
    color: "Mixed",
    badge: true,
    des: "Headphones are audio devices worn over the ears, delivering immersive sound and providing a personalized listening experience for music, calls, or other audio content.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Sun glasses",
    price: "220.00",
    color: "Black",
    badge: true,
    des: "Sunglasses are stylish accessories that provide protection against harmful UV rays while adding a touch of flair to one's appearance.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Flower Base",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "A flower base serves as a decorative vessel designed to hold and display a bouquet of flowers, adding a touch of elegance and charm to any space.",
  },
  {
    _id: 1046,
    img: spfOne,
    productName: "Cap for Boys",
    price: "35.00",
    color: "Blank and White",
    badge: true,
    des: "Boys' caps come in various styles and designs, providing a versatile accessory to complement their outfits and add a touch of personal flair.",
  },
];
// =================== PaginationItems End here =================
